feat:faq-section
code100x/job-board pull request #330
Opened 2024-09-12 16:35 UTC by ajeeshRS

### Added Faq-section

<img width="1440" alt="Screenshot 2024-09-12 at 9 54 57 PM" src="https://github.com/user-attachments/assets/47ae2060-b51a-4744-bb16-5c78890ff4d7">
<img width="1440" alt="Screenshot 2024-09-12 at 10 01 54 PM" src="https://github.com/user-attachments/assets/d071e650-5a40-4b3f-8303-4a60f1aa15f0">

 Let me know if it requires any further improvements.

2024-09-16 19:23 UTC, VineeTagarwaL-code requested changes

2024-09-16 19:23 UTC, VineeTagarwaL-code commented on src/lib/constant/faqs.constants.ts
> +export const faqData = [
should add types here tbh

2024-09-17 01:35 UTC, ajeeshRS commented on src/lib/constant/faqs.constants.ts
> +export const faqData = [
done

2024-09-17 04:31 UTC, VineeTagarwaL-code commented
rather than cards i will strongly suggest two things 

1. make it accordian 
2. have this in the main landing page only just after the listed jobs 
3. when clicked on the navbar make it autoscroll to the faq component in the landing page itself 

that's all 

after you make these changes, post a video of it ... if you have any doubts let me know

2024-09-17 14:53 UTC, ajeeshRS commented
Hey @VineeTagarwaL-code 
Here is the video of updated faq-section
https://github.com/user-attachments/assets/a8e4cfb7-d591-4ff8-9de0-cca83f146f1b

2024-09-17 15:44 UTC, VineeTagarwaL-code commented
Looks so cool man !!!, please also give the mobile ui

2024-09-17 17:43 UTC, merged