Feat/admin UI
code100x/job-board pull request #553
Opened 2024-10-24 18:41 UTC by Paribesh01

https://github.com/user-attachments/assets/f6e53482-63ad-4ac7-8d1c-085cdc576b29

2024-10-24 19:12 UTC, Paribesh01 commented
@VineeTagarwaL-code done with the work

2024-10-26 04:26 UTC, VineeTagarwaL-code commented
payment history wasnt needed, and the recruiters are the ones with hr role right ?

2024-10-26 05:27 UTC, Paribesh01 commented
@VineeTagarwaL-code payment history was there in the screenshot you provided, yes the recruiters are the one with hr role.

2024-10-26 05:40 UTC, VineeTagarwaL-code commented
Remove the payment history rest are good

2024-10-26 05:56 UTC, Paribesh01 commented
@VineeTagarwaL-code removed payment history

2024-10-27 10:04 UTC, VineeTagarwaL-code requested changes

2024-10-27 10:04 UTC, VineeTagarwaL-code commented on src/components/DeleteDialog.tsx
> +import { ArchiveRestore, Trash2 } from 'lucide-react';
use icon file we have and import it from there, do the favour for archiveRestore too

2024-10-27 10:04 UTC, VineeTagarwaL-code commented on src/config/path.config.ts
> +  PAYMENT_HISTORY: '/manage/payments',
why is manage payment code existing here ?

2024-10-27 10:05 UTC, VineeTagarwaL-code commented
Seems full of bugs here, fix it 
https://github.com/user-attachments/assets/adfd87e6-c446-48a7-bc37-bd1a780ca7fa

2024-10-27 12:00 UTC, Paribesh01 commented
@VineeTagarwaL-code ok I will work on changes, also for the recruiters, should I fetch users from db with hr role ??

2024-10-27 15:05 UTC, Paribesh01 commented
@VineeTagarwaL-code hr should have some relation with the company they are managing, so should i create a company model which have relation with the hr

2024-10-27 18:05 UTC, Paribesh01 commented
https://github.com/user-attachments/assets/feae8b1d-3e9d-4b50-8b01-23f0aa9567ae

@VineeTagarwaL-code done with the changes

2024-10-28 17:20 UTC, VineeTagarwaL-code commented
Have you fixed that bug ? its still replicating

2024-10-29 14:39 UTC, Paribesh01 commented
https://github.com/user-attachments/assets/de38e512-198c-479b-9e42-0aa651a0df9b

@VineeTagarwaL-code its working fine..

2024-10-30 18:47 UTC, VineeTagarwaL-code commented
![Screen Shot 2024-10-31 at 00 17 02](https://github.com/user-attachments/assets/5d43dc2e-0838-4198-847e-21ff4c790248)
everything works, fix the mobile responsiveness of this

2024-10-30 21:00 UTC, Paribesh01 commented
@VineeTagarwaL-code  done 
![Screenshot 2024-10-31 022507](https://github.com/user-attachments/assets/f76fd201-3e67-4c13-bb62-e3b6bb5307f6)

2024-10-31 05:29 UTC, VineeTagarwaL-code commented
can you do the same for recruiters page ? and dont squeeze it too much just minimal space between the borders of the screen will work

2024-10-31 06:11 UTC, Paribesh01 commented
@VineeTagarwaL-code done

2024-10-31 06:38 UTC, merged

2024-10-31 06:38 UTC, VineeTagarwaL-code commented
Great pr, make sure you on post on x and tag me !